### PR TITLE
get rid of old quake2 tga.c (11 years old workaround), fix #158

### LINKED ISSUE #158: is tga.c from Quake2 needed today?
The `tga.c` and `memtopixmap.c` files were added by @lnussel the 2004-08-14 (see f77842c) because some games from Id Software used a tga format that gdk-pixbuf was not able to load.

Is gdk-pixbuf now able to load them? This workaround was done 11 years ago, perhaps it's not needed today?

This `tga.c` were used to load map screenshots from Quake3, RTCW, ET and Doom3.

### PR DESCRIPTION
**Pull request by illwieckz**
11 years ago, @lnussel added a workaround based on quake2 source code to be able to load some tga files that GdkPixbuf were not able to load. So, 11 years later, it seems this workaround is not needed. This patch removes the quake2 tga code and enlighten a little the code.

This `tga.c` were used to load map screenshots from Quake3, RTCW, ET and Doom3 (See #158).

I've checked it against Q3, RTCW and Wolf:ET maps, it works well, I've not tested Doom3 maps yet, but there is no reason it could fail.

### CODE REVIEW

**Comment by zturtleman** [comment]
The brightness modification is probably because Q3 and RTCW use a gamma ramp with overbight bits to brighten the assets. The actual image file is darker than displayed in-game. Gamma ramps are broken in windowed mode on GNU/Linux using Xorg or whatever, so compare with fullscreen. ET does not use overbright. I don't know if Doom 3 does. (I have not tested this pull request.)

**Comment by illwieckz** [comment]
With the brightness modification, all screenshots from all games where too bright, without this brightness modification, all screenshots from all suppported games (including quake3) seem to look fine. I need to test RTCW more because screenshots have a dark athmosphere, whatever the brightness setting, so I do'nt know yet if it's dark because the map is dark or because the brightness is wrong. I hope to not need per game brightness.

**Comment by illwieckz** [comment]
OK, map shots of Quake3, RTCW, ET and Doom3 are ok with these patches.

They all look better **without** the brightness modification.

**Comment by illwieckz** [comment]
Well, why I can't merge that o.O

**Comment by zturtleman** [comment]
I think `tmp = p[0] + brightness;` etc should be `tmp = ((int)p[0]) << 1;` in renderMemToGtkPixmap to match Q3 gamma ramps. (I haven't tested it.)

If the levelshots look fine and managing per-game brightness correction seems excessive, I guess it's not really important.

**Comment by illwieckz** [comment]
Ah, I can test it

**Comment by illwieckz** [comment]
What to do with the `brightness` value ?

**Comment by zturtleman** [comment]
Ignore it or rename it to overBrightBits and set it to 1. `tmp = ((int)p[0]) << overBrightBits;`

**Comment by illwieckz** [comment]
OK. with your changes, RTCW map shots looks better, but some other shots (like padman ones) are too brighty.

**Comment by illwieckz** [comment]
Doom3 mapshots are very nice too.

**Comment by zturtleman** [comment]
World of Padman would need to use overBrightBits 0.

**Comment by illwieckz** [comment]
yep (clickable image):

[XQF brightness bump](http://dl.illwieckz.net/u/thomas-debesse/bug-reports/xqf/165-tga/20150626-22222.xqf-brightness-bump-comparison.png)

**Comment by illwieckz** [comment]
@zturtleman: I've included your code because it's look very nice, but currently it is disabled because we need to add some per-game code. Currently the mapshots are displayed without brightness modification, which is the safer choice.

**Comment by illwieckz** [comment]
@zturtleman: do you think Quake4 mapshots needs brightness bump ?

**Comment by zturtleman** [comment]
Okay. Yeah, would also need to find out what the values for all games should be. Spearmint would need per-mod setting, not hugely important just mentioning it. I think RTCW should actually use overBrightBits 0. I don't own Quake 4 and it's closed source, so I can't check.

**Comment by illwieckz** [comment]
Quake4 maps with overBrightBits 1 looks very nice
WolfET needs overBrightBits 0

**Comment by zturtleman** [comment]
The code looks good. OpenArena, Q3 Rally, Voyager Elite Force, Reaction, and Smokin' Guns should use overbrightbits 1 too. This isn't a complete list, I didn't check all the games.

**Pull request merged**
