### PR TITLE
Use the correct copyright symbol in hex notation.

### PR DESCRIPTION
**Pull request by jmallach**

### CODE REVIEW

**Comment by illwieckz** [comment]
Good idea!

**Comment by illwieckz** [comment]
Hi @jmallach, can I merge that? :+1:

**Comment by jmallach** [comment]
I guess. This one, and possibly the other patch in the fork.

**Comment by illwieckz** [comment]
With GitHub the easier is to merge both (I don't think there is a cherry-pick web interface on GitHub). :wink:

**Pull request merged**
